hydra:
  run:
    dir: outputs/mabrax/${ENV_NAME}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/mabrax/${ENV_NAME}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ''
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - network=ff_nps
    - ++TOTAL_TIMESTEPS=3e7
    - ++UPDATE_EPOCHS=4,8
    - ++SEED=range(0,16)
  job:
    name: ippo_sweep
    chdir: true
    override_dirname: ++SEED=range(0,16),++TOTAL_TIMESTEPS=3e7,++UPDATE_EPOCHS=4,8,network=ff_nps
    id: ???
    num: ???
    config_name: ippo_sweep
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: /home/lhin/assistax/JaxMARL/baselines/IPPO
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /home/lhin/assistax/JaxMARL/baselines/IPPO/config
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      network: ff_nps
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
network:
  recurrent: false
  agent_param_sharing: false
  actor_hidden_dim: 128
  critic_hidden_dim: 128
  activation: tanh
ENV_NAME: scratchitch
ENV_KWARGS:
  ctrl_cost_weight: 0
  homogenisation_method: max
  backend: mjx
TOTAL_TIMESTEPS: 30000000.0
NUM_STEPS: 256
NUM_ENVS: 512
NUM_SEEDS: 5
SEED: 0
NUM_EVAL_EPISODES: 32
UPDATE_EPOCHS: 4
NUM_MINIBATCHES: 4
ANNEAL_LR: false
LR: 0.00025
ENT_COEF: 0.0001
CLIP_EPS: 0.2
SCALE_CLIP_EPS: false
RATIO_CLIP_EPS: false
GAMMA: 0.99
GAE_LAMBDA: 0.95
VF_COEF: 1.0
MAX_GRAD_NORM: 0.5
ADAM_EPS: 1.0e-08
GPU_ENV_CAPACITY: 4096
ADVANTAGE_UNROLL_DEPTH: 8
DISABLE_JIT: false
DEVICE: 0
SWEEP:
  num_configs: 2
  lr:
    min: -5.0
    max: -2.0
  ent_coef: false
  clip_eps:
    min: -2.0
    max: 0.0
